### ISSUE TITLE
Causes Nuclear Reactor from Vanilla Furniture Expanded - Power to meltdown instantly.

### ISSUE THREAD

**Issue by SorryForWhat** [GarwelGarwel/Celsius#10]
Not a bug, so no log, but still a hardcore incompatibility.
Reactor reach 60~80*C in a few central tiles and go boom:
![image](https://user-images.githubusercontent.com/32202635/150636941-69ccbfa8-d401-4b47-8c10-e3c6ec7564ea.png)

**Comment by GarwelGarwel** [comment]
I'll check it out. Most likely, it needs to have the core's critical temperature increased.
