### ISSUE TITLE
suggestion: setting to have heatmap turned off by default

### ISSUE THREAD

**Issue by malistaticy** [GarwelGarwel/Celsius#15]
title
on game load, its usually on by default, just a minor qol thing id like to see to save a click

**Comment by GarwelGarwel** [comment]
It should already be off by default unless you changed the settings.

**Comment by malistaticy** [comment]
> It should already be off by default unless you changed the settings.

oh no, something might be wrong with my game then, whenever i load into a save after launching the game it will be turned on
