### ISSUE TITLE
Temperature rises to critical level in a tile where pawn usually stay still

### ISSUE THREAD

**Issue by SergeantBlyat** [GarwelGarwel/Celsius#20]
I've been using this mod for a bit and discover that in places where pawns stay still for a bit of time, the temperature in that tile will continue to rises to critical level, sometimes up to 100 degree, causing pawn to be lit up.

I do not know which mod causes this, Though I saw one guy commented something similar, but to a lesser degree.

Here's my mod list file exported from RimPy
[List In Question.txt](https://github.com/GarwelGarwel/Celsius/files/9038054/List.In.Question.txt)

**Comment by GarwelGarwel** [comment]
Pawns emit heat (even in vanilla), so a little warming up is right. But it shouldn't be up to 100C of course. So it's either your Celsius settings are off (maybe heat push is too high or convection too low, for instance) or some other mod interferes by changing the heat emission (mods that change body sizes will do it). I can't test your 400 mods, unfortunately. If you enable debug logging mode in Celsius settings and share the log where it happens, I can look at it and maybe will find something out.

**Comment by GarwelGarwel** [comment]
This issue must have been fixed in the latest update and in any case shouldn't apply to the upcoming overhaul. Please reopen if you encounter it again.
