### ISSUE TITLE
Suggestion: heat output per tile

### ISSUE THREAD

**Issue by Gogoghig** [GarwelGarwel/Celsius#41]
In "Android Tiers" mod there are "Sky Mind Core" that is 8x8 tiles, requires temperature below 0*C and pushes big amount of heat into one tile, that rises the temperature to 60*C and melt the core. 
Is it possible to smoothly distribute the thermal output of such large machines evenly over their occupied area?
![Screenshot 2023-10-19 002921](https://github.com/GarwelGarwel/Celsius/assets/148382435/186660c6-3940-4d0f-98e8-c63701e28660)
![Screenshot 2023-10-19 002944](https://github.com/GarwelGarwel/Celsius/assets/148382435/624e46c1-bb8e-474a-bb8f-5336157a656c)
![Screenshot 2023-10-19 003007](https://github.com/GarwelGarwel/Celsius/assets/148382435/525957e1-5373-4d40-9160-87c39920cd06)
Also, one solution could be to use ceiling fans for air convection
Thank you
best reguards

**Comment by GarwelGarwel** [comment]
It should work in the next release.
